services:
  pg:
    image: postgres
    environment:
       POSTGRES_DB: test
       POSTGRES_USER: test_user
       POSTGRES_PASSWORD: test_pass
    ports:
      - "5433:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: testadmin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_SERVER_MODE: 'False'
    ports:
      - "5050:80"